builders:
  routeBuilder:
    import: "package:flutter_route_generator/src/builders/route_builder.dart"
    builder_factories: ["routeBuilder"]
    build_extensions: {".dart": [".route.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]