name: flutter_route_generator
description: A dynamically generated route configuration for Flutter apps
version: 0.1.0
homepage: https://github.com/yourusername/flutter_route_generator

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  source_gen: ^2.0.0
  analyzer: ^6.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.24.1

# This section is crucial for the build_runner to find and use your builder
builders:
  route_generator:
    import: "package:flutter_route_generator/builder.dart"
    builder_factories: ["routeGenerator"]
    build_extensions: {"$lib$": ["routes_registry.g.dart"], ".dart": [".routes.dart"]}
    auto_apply: dependents
    build_to: source