name: flutter_route_generator
description: A dynamically generated route configuration for Flutter apps
version: 0.1.0
homepage: https://github.com/yourusername/flutter_route_generator

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  source_gen: ^2.0.0
  analyzer: ^6.11.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.24.1

# Builder configuration with default settings to avoid requiring app-level build.yaml
builders:
  route_generator:
    import: "package:flutter_route_generator/builder.dart"
    builder_factories: ["routeGeneratorFactory"]
    build_extensions: {".dart": [".routes.g.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        include:
          - lib/**.dart
      options:
        auto_discovery: true
    applies_builders: ["source_gen:combining_builder"]
    
  route_registry_generator:
    import: "package:flutter_route_generator/builder.dart"
    builder_factories: ["registryGeneratorFactory"]
    build_extensions: {"lib/$lib$": ["lib/routes_registry.g.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        include:
          - lib/
      options:
        auto_discovery: true