name: flutter_route_generator
description: A dynamically generated route configuration for Flutter apps
version: 0.1.0
homepage: https://github.com/yourusername/flutter_route_generator

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^2.0.0
  analyzer: ^7.4.5
  path: ^1.8.3
  glob: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  test: ^1.24.1

# This is crucial for the build_runner to find our builder
builders:
  route_generator:
    import: "package:flutter_route_generator/builder.dart"
    builder_factories: ["routeGeneratorBuilder"]
    build_extensions: {"$lib$": ["route_registry.dart"]}
    auto_apply: dependents
    build_to: source